### ISSUE TITLE
Class names duplicates

### ISSUE THREAD

**Issue by bfourgeaud** [apvarun/tailwindcss-analysis#6]
The analysis leaves some duplicates in the used classNames.

![image](https://github.com/apvarun/tailwindcss-analysis/assets/54413707/4158236d-497b-431c-92f5-90612f4f5f16)

![image](https://github.com/apvarun/tailwindcss-analysis/assets/54413707/cb024e70-bc69-4398-bb66-a8d2d47bd4e3)

### tailwind-output.css
https://pastebin.com/eFFgnqCz

**Comment by apvarun** [comment]
Fixed in v0.4.0
